#!/bin/bash

### Script to convert a server certificate generated by the TAK Server CA into a Server Certificate, Private Key and CA Bundle

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have receieved a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2022 Nicholas Poulter - nick@emfour.net

clear

if [ "$1" == "-h" ]; then
    echo "Usage: certBundleGen.sh {domain} {certificate}"
    echo " "
    echo "{certificate} Filename of the p12 encoded certificate"
    echo "{domain} The Fully Qualified Domain Name for the certificate (domain.com)"
    echo " "
    echo "Example: ./certBundleGen.sh emfour.local xmppserver.p12"

    exit 1
fi

if [ ! "$1" ]; then
   echo "Provide the filename of the certificate to convert (.p12)."
   exit 1
fi

if [ ! "$2" ]; then
   echo "Provide the Fully Qualified Domain Name of the certificates (domain.com)."
   exit 1
fi

dir=$1-Bundle
mkdir $dir
echo "Creating Server Certificate..."
openssl pkcs12 -in $2 -clcerts -nokeys -out $dir/$1.crt
echo "Creating Certificate Key..."
openssl pkcs12 -in $2 -nocerts -nodes -out $dir/$1.key
echo "Creating Certificate Authority Bundle..."
openssl pkcs12 -in $2 -out $dir/$1-ca.crt -nodes -nokeys -cacerts

echo "Certificate Bundle Successfully Created in $dir"
